x-restart: &restart
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "5"

services:
  django:
    <<: *restart
  airflow-postgres:
    <<: *restart
  airflow-webserver:
    <<: *restart
  airflow-scheduler:
    <<: *restart
