
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'RECON_DMS_XUATKHO' AND COLUMN_NAME = 'SoStatus'
)
BEGIN
    ALTER TABLE dbo.RECON_DMS_XUATKHO ADD SoStatus NVARCHAR(50) NULL;
END

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'RECON_DMS_XUATKHO_Backup' AND COLUMN_NAME = 'SoStatus'
)
BEGIN
    ALTER TABLE dbo.RECON_DMS_XUATKHO_Backup ADD SoStatus NVARCHAR(50) NULL;
END
