

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'WMS_INBOUND_Pending' AND COLUMN_NAME = 'ReCheck'
)
BEGIN
    ALTER TABLE dbo.WMS_INBOUND_Pending ADD ReCheck BIT NOT NULL DEFAULT 1;
END

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'WMS_INBOUND_Pending' AND COLUMN_NAME = 'Note'
)
BEGIN
    ALTER TABLE dbo.WMS_INBOUND_Pending ADD Note NVARCHAR(100) NULL;
END

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'WMS_OUTBOUND_Pending' AND COLUMN_NAME = 'ReCheck'
)
BEGIN
    ALTER TABLE dbo.WMS_OUTBOUND_Pending ADD ReCheck BIT NOT NULL DEFAULT 1;
END

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'WMS_OUTBOUND_Pending' AND COLUMN_NAME = 'Note'
)
BEGIN
    ALTER TABLE dbo.WMS_OUTBOUND_Pending ADD Note NVARCHAR(100) NULL;
END
