

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RECON_ECOM' AND COLUMN_NAME = 'OrderDate')
BEGIN ALTER TABLE dbo.RECON_ECOM ADD OrderDate DATE NULL; END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RECON_DMS_DUYET' AND COLUMN_NAME = 'OrderDate')
BEGIN ALTER TABLE dbo.RECON_DMS_DUYET ADD OrderDate DATE NULL; END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RECON_DMS_XUATKHO' AND COLUMN_NAME = 'OrderDate')
BEGIN ALTER TABLE dbo.RECON_DMS_XUATKHO ADD OrderDate DATE NULL; END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RECON_WRT' AND COLUMN_NAME = 'OrderDate')
BEGIN ALTER TABLE dbo.RECON_WRT ADD OrderDate DATE NULL; END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RECON_ECOM_Backup' AND COLUMN_NAME = 'OrderDate')
BEGIN ALTER TABLE dbo.RECON_ECOM_Backup ADD OrderDate DATE NULL; END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RECON_DMS_DUYET_Backup' AND COLUMN_NAME = 'OrderDate')
BEGIN ALTER TABLE dbo.RECON_DMS_DUYET_Backup ADD OrderDate DATE NULL; END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RECON_DMS_XUATKHO_Backup' AND COLUMN_NAME = 'OrderDate')
BEGIN ALTER TABLE dbo.RECON_DMS_XUATKHO_Backup ADD OrderDate DATE NULL; END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RECON_WRT_Backup' AND COLUMN_NAME = 'OrderDate')
BEGIN ALTER TABLE dbo.RECON_WRT_Backup ADD OrderDate DATE NULL; END
