IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'DMS_SO_Pending')
BEGIN
    CREATE TABLE dbo.DMS_SO_Pending (
        OrderCode VARCHAR(50) NOT NULL PRIMARY KEY,
        DocDate DATE NOT NULL,
        FirstSeenAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        LastCheckedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
    );
END
