IF OBJECT_ID('dbo.SAP_INVENTORY') IS NULL
BEGIN
    CREATE TABLE dbo.SAP_INVENTORY (
        ItemCode NVARCHAR(50) NOT NULL,
        ItemName NVARCHAR(200) NULL,
        WhsCode NVARCHAR(8) NOT NULL,
        WhsName NVARCHAR(100) NULL,
        StatusItem NVARCHAR(100) NOT NULL CONSTRAINT DF_SAP_INVENTORY_StatusItem DEFAULT '',
        OnHand DECIMAL(21,6) NULL,
        InvntryUom NVARCHAR(100) NULL,
        LoadedAt DATETIME2 NOT NULL CONSTRAINT DF_SAP_INVENTORY_LoadedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_SAP_INVENTORY PRIMARY KEY (ItemCode, WhsCode, StatusItem)
    );
END

IF OBJECT_ID('dbo.SAP_INVENTORY_Staging') IS NULL
BEGIN
    CREATE TABLE dbo.SAP_INVENTORY_Staging (
        ItemCode NVARCHAR(50) NOT NULL,
        ItemName NVARCHAR(200) NULL,
        WhsCode NVARCHAR(8) NOT NULL,
        WhsName NVARCHAR(100) NULL,
        StatusItem NVARCHAR(100) NOT NULL CONSTRAINT DF_SAP_INVENTORY_Staging_StatusItem DEFAULT '',
        OnHand DECIMAL(21,6) NULL,
        InvntryUom NVARCHAR(100) NULL,
        LoadedAt DATETIME2 NOT NULL CONSTRAINT DF_SAP_INVENTORY_Staging_LoadedAt DEFAULT SYSUTCDATETIME()
    );
END

IF OBJECT_ID('dbo.SAP_INVENTORY_Load_Log') IS NULL
BEGIN
    CREATE TABLE dbo.SAP_INVENTORY_Load_Log (
        id INT IDENTITY(1,1) PRIMARY KEY,
        row_count INT NOT NULL,
        status VARCHAR(20) NOT NULL,
        message NVARCHAR(1000) NULL,
        loaded_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
    );
END
