IF OBJECT_ID('dbo.RECON_INVENTORY') IS NULL
BEGIN
    CREATE TABLE dbo.RECON_INVENTORY (
        StatusSync NVARCHAR(30) NOT NULL,
        ItemCode NVARCHAR(50) NOT NULL,
        ItemName NVARCHAR(300) NULL,
        WhsCode NVARCHAR(10) NOT NULL,
        WhsName NVARCHAR(100) NULL,
        StatusItem NVARCHAR(100) NOT NULL,
        SapQty DECIMAL(21,6) NULL,
        WmsQty DECIMAL(21,6) NULL,
        DiffQty DECIMAL(21,6) NOT NULL,
        InvntryUom NVARCHAR(100) NULL,
        RefreshedAt DATETIME2 NOT NULL CONSTRAINT DF_RECON_INVENTORY_RefreshedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_RECON_INVENTORY PRIMARY KEY (ItemCode, WhsCode, StatusItem)
    );
    CREATE INDEX IX_RECON_INVENTORY_StatusSync ON dbo.RECON_INVENTORY (StatusSync);
END
