IF OBJECT_ID('dbo.WMS_TRANSACTION', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.WMS_TRANSACTION (
        id NVARCHAR(64) NOT NULL PRIMARY KEY,
        _whseid NVARCHAR(30) NOT NULL,
        _txn_date DATE NOT NULL,
        itrnkey NVARCHAR(64) NULL,
        trantype NVARCHAR(100) NULL,
        sourcetype NVARCHAR(100) NULL,
        sourcekey NVARCHAR(200) NULL,
        whseid NVARCHAR(30) NULL,
        fromwhseid NVARCHAR(30) NULL,
        towhseid NVARCHAR(30) NULL,
        storerkey NVARCHAR(50) NULL,
        tostorerkey NVARCHAR(50) NULL,
        sku NVARCHAR(100) NULL,
        tosku NVARCHAR(100) NULL,
        status NVARCHAR(50) NULL,
        tostatus NVARCHAR(50) NULL,
        qty DECIMAL(28, 8) NULL,
        toqty DECIMAL(28, 8) NULL,
        uom NVARCHAR(50) NULL,
        uomqty DECIMAL(28, 8) NULL,
        touom NVARCHAR(50) NULL,
        touomqty DECIMAL(28, 8) NULL,
        fromloc NVARCHAR(100) NULL,
        toloc NVARCHAR(100) NULL,
        fromlpnid NVARCHAR(100) NULL,
        tolpnid NVARCHAR(100) NULL,
        lot NVARCHAR(100) NULL,
        tolot NVARCHAR(100) NULL,
        palletid NVARCHAR(100) NULL,
        topalletid NVARCHAR(100) NULL,
        cartonid NVARCHAR(100) NULL,
        tocartonid NVARCHAR(100) NULL,
        unitid NVARCHAR(100) NULL,
        tounitid NVARCHAR(100) NULL,
        intransit NVARCHAR(100) NULL,
        loadid NVARCHAR(100) NULL,
        mastercode NVARCHAR(100) NULL,
        remark NVARCHAR(1000) NULL,
        lottable01 NVARCHAR(200) NULL,
        lottable02 NVARCHAR(200) NULL,
        lottable03 NVARCHAR(200) NULL,
        lottable04 DATETIME2 NULL,
        lottable05 DATETIME2 NULL,
        lottable06 NVARCHAR(200) NULL,
        lottable07 NVARCHAR(200) NULL,
        lottable08 NVARCHAR(200) NULL,
        lottable09 NVARCHAR(200) NULL,
        lottable10 NVARCHAR(200) NULL,
        lottable11 DATETIME2 NULL,
        lottable12 DATETIME2 NULL,
        tolottable01 NVARCHAR(200) NULL,
        tolottable02 NVARCHAR(200) NULL,
        tolottable03 NVARCHAR(200) NULL,
        tolottable04 DATETIME2 NULL,
        tolottable05 DATETIME2 NULL,
        tolottable06 NVARCHAR(200) NULL,
        tolottable07 NVARCHAR(200) NULL,
        tolottable08 NVARCHAR(200) NULL,
        tolottable09 NVARCHAR(200) NULL,
        tolottable10 NVARCHAR(200) NULL,
        tolottable11 DATETIME2 NULL,
        tolottable12 DATETIME2 NULL,
        adddate DATETIME2 NULL,
        addwho NVARCHAR(100) NULL,
        editdate DATETIME2 NULL,
        editwho NVARCHAR(100) NULL,
        _scraped_at DATETIME2 NOT NULL CONSTRAINT DF_WMS_TRANSACTION_scraped_at DEFAULT SYSUTCDATETIME()
    );
    CREATE INDEX IX_WMS_TRANSACTION_whse_date ON dbo.WMS_TRANSACTION (_whseid, _txn_date);
    CREATE INDEX IX_WMS_TRANSACTION_sku_whse ON dbo.WMS_TRANSACTION (sku, _whseid)
        INCLUDE (trantype, status, tostatus, qty, adddate, sourcetype, sourcekey, fromlpnid, tolpnid, fromloc, toloc);
END

IF OBJECT_ID('dbo.WMS_TRANSACTION_Load_Log', 'U') IS NULL
    CREATE TABLE dbo.WMS_TRANSACTION_Load_Log (
        id INT IDENTITY(1, 1) PRIMARY KEY,
        whseid NVARCHAR(30) NOT NULL,
        txn_date DATE NOT NULL,
        row_count INT NOT NULL,
        status NVARCHAR(20) NOT NULL,
        loaded_at DATETIME2 NOT NULL CONSTRAINT DF_WMS_TRANSACTION_Load_Log_loaded_at DEFAULT SYSUTCDATETIME()
    );
